/** @file
 *
 *  Copyright (c) 2023, Mario Bălănică <mariobalanica02@gmail.com>
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/

#ifndef __BCM2712_PINCTRL_H__
#define __BCM2712_PINCTRL_H__

//
// Supported Alternate Pin Functions
//

//
// General Input/Output (GIO)
//

typedef enum {
  GIO_PIN1_ALT_VC_I2C0 = 1,
  GIO_PIN1_ALT_USB_PWR,
  GIO_PIN1_ALT_GPCLK0,
  GIO_PIN1_ALT_SD_CARD_E,
  GIO_PIN1_ALT_VC_SPI3,
  GIO_PIN1_ALT_SR_EDM_SENSE,
  GIO_PIN1_ALT_VC_SPI0,
  GIO_PIN1_ALT_VC_UART0,
} GIO_PIN1_ALT;

typedef enum {
  GIO_PIN2_ALT_VC_I2C0 = 1,
  GIO_PIN2_ALT_USB_PWR,
  GIO_PIN2_ALT_GPCLK1,
  GIO_PIN2_ALT_SD_CARD_E,
  GIO_PIN2_ALT_VC_SPI3,
  GIO_PIN2_ALT_CLK_OBSERVE,
  GIO_PIN2_ALT_VC_SPI0,
  GIO_PIN2_ALT_VC_UART0,
} GIO_PIN2_ALT;

typedef enum {
  GIO_PIN3_ALT_VC_I2C3 = 1,
  GIO_PIN3_ALT_USB_VBUS,
  GIO_PIN3_ALT_GPCLK2,
  GIO_PIN3_ALT_SD_CARD_E,
  GIO_PIN3_ALT_VC_SPI3,
  GIO_PIN3_ALT_VC_SPI0,
  GIO_PIN3_ALT_VC_UART0,
} GIO_PIN3_ALT;

typedef enum {
  GIO_PIN4_ALT_VC_I2C3 = 1,
  GIO_PIN4_ALT_VC_PWM1,
  GIO_PIN4_ALT_VC_SPI3,
  GIO_PIN4_ALT_SD_CARD_E,
  GIO_PIN4_ALT_VC_SPI3_2,
  GIO_PIN4_ALT_VC_SPI0,
  GIO_PIN4_ALT_VC_UART0,
} GIO_PIN4_ALT;

typedef enum {
  GIO_PIN10_ALT_BSC_M3 = 1,
  GIO_PIN10_ALT_VC_PWM1,
  GIO_PIN10_ALT_VC_SPI3,
  GIO_PIN10_ALT_SD_CARD_E,
  GIO_PIN10_ALT_VC_SPI3_2,
  GIO_PIN10_ALT_GPCLK0,
} GIO_PIN10_ALT;

typedef enum {
  GIO_PIN11_ALT_BSC_M3 = 1,
  GIO_PIN11_ALT_VC_SPI3,
  GIO_PIN11_ALT_CLK_OBSERVE,
  GIO_PIN11_ALT_SD_CARD_C,
  GIO_PIN11_ALT_GPCLK1,
} GIO_PIN11_ALT;

typedef enum {
  GIO_PIN12_ALT_SPI_S = 1,
  GIO_PIN12_ALT_VC_SPI3,
  GIO_PIN12_ALT_SD_CARD_C,
  GIO_PIN12_ALT_SD_CARD_D,
} GIO_PIN12_ALT;

typedef enum {
  GIO_PIN13_ALT_SPI_S = 1,
  GIO_PIN13_ALT_VC_SPI3,
  GIO_PIN13_ALT_SD_CARD_C,
  GIO_PIN13_ALT_SD_CARD_D,
} GIO_PIN13_ALT;

typedef enum {
  GIO_PIN14_ALT_SPI_S = 1,
  GIO_PIN14_ALT_UUI,
  GIO_PIN14_ALT_ARM_JTAG,
  GIO_PIN14_ALT_VC_PWM0,
  GIO_PIN14_ALT_VC_I2C0,
  GIO_PIN14_ALT_SD_CARD_D,
} GIO_PIN14_ALT;

typedef enum {
  GIO_PIN15_ALT_SPI_S = 1,
  GIO_PIN15_ALT_UUI,
  GIO_PIN15_ALT_ARM_JTAG,
  GIO_PIN15_ALT_VC_PWM0,
  GIO_PIN15_ALT_VC_I2C0,
  GIO_PIN15_ALT_GPCLK0,
} GIO_PIN15_ALT;

typedef enum {
  GIO_PIN18_ALT_SD_CARD_F = 1,
  GIO_PIN18_ALT_VC_PWM1,
} GIO_PIN18_ALT;

typedef enum {
  GIO_PIN19_ALT_SD_CARD_F = 1,
  GIO_PIN19_ALT_USB_PWR,
  GIO_PIN19_ALT_VC_PWM1,
} GIO_PIN19_ALT;

typedef enum {
  GIO_PIN20_ALT_VC_I2C3 = 1,
  GIO_PIN20_ALT_UUI,
  GIO_PIN20_ALT_VC_UART0,
  GIO_PIN20_ALT_ARM_JTAG,
  GIO_PIN20_ALT_VC_UART2,
} GIO_PIN20_ALT;

typedef enum {
  GIO_PIN21_ALT_VC_I2C3 = 1,
  GIO_PIN21_ALT_UUI,
  GIO_PIN21_ALT_VC_UART0,
  GIO_PIN21_ALT_ARM_JTAG,
  GIO_PIN21_ALT_VC_UART2,
} GIO_PIN21_ALT;

typedef enum {
  GIO_PIN22_ALT_SD_CARD_F = 1,
  GIO_PIN22_ALT_VC_UART0,
  GIO_PIN22_ALT_VC_I2C3,
} GIO_PIN22_ALT;

typedef enum {
  GIO_PIN23_ALT_VC_UART0 = 1,
  GIO_PIN23_ALT_VC_I2C3,
} GIO_PIN23_ALT;

typedef enum {
  GIO_PIN24_ALT_SD_CARD_B = 1,
  GIO_PIN24_ALT_VC_SPI0,
  GIO_PIN24_ALT_ARM_JTAG,
  GIO_PIN24_ALT_UART0,
  GIO_PIN24_ALT_USB_PWR,
  GIO_PIN24_ALT_VC_UART2,
  GIO_PIN24_ALT_VC_UART0,
} GIO_PIN24_ALT;

typedef enum {
  GIO_PIN25_ALT_SD_CARD_B = 1,
  GIO_PIN25_ALT_VC_SPI0,
  GIO_PIN25_ALT_ARM_JTAG,
  GIO_PIN25_ALT_UART0,
  GIO_PIN25_ALT_USB_PWR,
  GIO_PIN25_ALT_VC_UART2,
  GIO_PIN25_ALT_VC_UART0,
} GIO_PIN25_ALT;

typedef enum {
  GIO_PIN26_ALT_SD_CARD_B = 1,
  GIO_PIN26_ALT_VC_SPI0,
  GIO_PIN26_ALT_ARM_JTAG,
  GIO_PIN26_ALT_UART0,
  GIO_PIN26_ALT_USB_VBUS,
  GIO_PIN26_ALT_VC_UART2,
  GIO_PIN26_ALT_VC_SPI0_2,
} GIO_PIN26_ALT;

typedef enum {
  GIO_PIN27_ALT_SD_CARD_B = 1,
  GIO_PIN27_ALT_VC_SPI0,
  GIO_PIN27_ALT_ARM_JTAG,
  GIO_PIN27_ALT_UART0,
  GIO_PIN27_ALT_VC_UART2,
  GIO_PIN27_ALT_VC_SPI0_2,
} GIO_PIN27_ALT;

typedef enum {
  GIO_PIN28_ALT_SD_CARD_B = 1,
  GIO_PIN28_ALT_VC_SPI0,
  GIO_PIN28_ALT_ARM_JTAG,
  GIO_PIN28_ALT_VC_I2C0,
  GIO_PIN28_ALT_VC_SPI0_2,
} GIO_PIN28_ALT;

typedef enum {
  GIO_PIN29_ALT_ARM_JTAG = 1,
  GIO_PIN29_ALT_VC_I2C0,
  GIO_PIN29_ALT_VC_SPI0,
} GIO_PIN29_ALT;

typedef enum {
  GIO_PIN30_ALT_SD2 = 1,
  GIO_PIN30_ALT_GPCLK0,
  GIO_PIN30_ALT_VC_PWM0,
} GIO_PIN30_ALT;

typedef enum {
  GIO_PIN31_ALT_SD2 = 1,
  GIO_PIN31_ALT_VC_SPI3,
  GIO_PIN31_ALT_VC_PWM0,
} GIO_PIN31_ALT;

typedef enum {
  GIO_PIN32_ALT_SD2 = 1,
  GIO_PIN32_ALT_VC_SPI3,
  GIO_PIN32_ALT_VC_UART3,
} GIO_PIN32_ALT;

typedef enum {
  GIO_PIN33_ALT_SD2 = 1,
  GIO_PIN33_ALT_VC_SPI3,
  GIO_PIN33_ALT_VC_UART3,
} GIO_PIN33_ALT;

typedef enum {
  GIO_PIN34_ALT_SD2 = 1,
  GIO_PIN34_ALT_VC_SPI3,
  GIO_PIN34_ALT_VC_I2C5,
} GIO_PIN34_ALT;

typedef enum {
  GIO_PIN35_ALT_SD2 = 1,
  GIO_PIN35_ALT_VC_SPI3,
  GIO_PIN35_ALT_VC_I2C5,
} GIO_PIN35_ALT;

//
// General Input/Output Always ON (GIO AON)
//
typedef enum {
  GIO_AON_PIN0_ALT_IR_IN = 1,
  GIO_AON_PIN0_ALT_VC_SPI0,
  GIO_AON_PIN0_ALT_VC_UART0,
  GIO_AON_PIN0_ALT_VC_I2C3,
  GIO_AON_PIN0_ALT_UART0,
  GIO_AON_PIN0_ALT_VC_I2C0,
} GIO_AON_PIN0_ALT;

typedef enum {
  GIO_AON_PIN1_ALT_VC_PWM0 = 1,
  GIO_AON_PIN1_ALT_VC_SPI0,
  GIO_AON_PIN1_ALT_VC_UART0,
  GIO_AON_PIN1_ALT_VC_I2C3,
  GIO_AON_PIN1_ALT_UART0,
  GIO_AON_PIN1_ALT_AON_PWM,
  GIO_AON_PIN1_ALT_VC_I2C0,
  GIO_AON_PIN1_ALT_VC_PWM1,
} GIO_AON_PIN1_ALT;

typedef enum {
  GIO_AON_PIN2_ALT_VC_PWM0 = 1,
  GIO_AON_PIN2_ALT_VC_SPI0,
  GIO_AON_PIN2_ALT_VC_UART0,
  GIO_AON_PIN2_ALT_CTL_HDMI_5V,
  GIO_AON_PIN2_ALT_UART0,
  GIO_AON_PIN2_ALT_AON_PWM,
  GIO_AON_PIN2_ALT_IR_IN,
  GIO_AON_PIN2_ALT_VC_PWM1,
} GIO_AON_PIN2_ALT;

typedef enum {
  GIO_AON_PIN3_ALT_IR_IN = 1,
  GIO_AON_PIN3_ALT_VC_SPI0,
  GIO_AON_PIN3_ALT_VC_UART0,
  GIO_AON_PIN3_ALT_UART0,
  GIO_AON_PIN3_ALT_SD_CARD_G,
  GIO_AON_PIN3_ALT_AON_GPCLK,
} GIO_AON_PIN3_ALT;

typedef enum {
  GIO_AON_PIN4_ALT_GPCLK0 = 1,
  GIO_AON_PIN4_ALT_VC_SPI0,
  GIO_AON_PIN4_ALT_PM_LED_OUT,
  GIO_AON_PIN4_ALT_AON_PWM,
  GIO_AON_PIN4_ALT_SD_CARD_G,
  GIO_AON_PIN4_ALT_VC_PWM0,
} GIO_AON_PIN4_ALT;

typedef enum {
  GIO_AON_PIN5_ALT_GPCLK1 = 1,
  GIO_AON_PIN5_ALT_IR_IN,
  GIO_AON_PIN5_ALT_AON_PWM,
  GIO_AON_PIN5_ALT_SD_CARD_G,
  GIO_AON_PIN5_ALT_VC_PWM0,
} GIO_AON_PIN5_ALT;

typedef enum {
  GIO_AON_PIN6_ALT_UART1 = 1,
  GIO_AON_PIN6_ALT_VC_UART2,
  GIO_AON_PIN6_ALT_CTL_HDMI_5V,
  GIO_AON_PIN6_ALT_GPCLK2,
  GIO_AON_PIN6_ALT_VC_SPI3,
} GIO_AON_PIN6_ALT;

typedef enum {
  GIO_AON_PIN8_ALT_UART1 = 1,
  GIO_AON_PIN8_ALT_VC_UART2,
  GIO_AON_PIN8_ALT_CTL_HDMI_5V,
  GIO_AON_PIN8_ALT_VC_SPI0,
  GIO_AON_PIN8_ALT_VC_SPI3,
} GIO_AON_PIN8_ALT;

typedef enum {
  GIO_AON_PIN9_ALT_UART1 = 1,
  GIO_AON_PIN9_ALT_VC_UART2,
  GIO_AON_PIN9_ALT_VC_UART0,
  GIO_AON_PIN9_ALT_AON_PWM,
  GIO_AON_PIN9_ALT_VC_SPI0,
  GIO_AON_PIN9_ALT_VC_UART2_2,
  GIO_AON_PIN9_ALT_VC_SPI3,
} GIO_AON_PIN9_ALT;

typedef enum {
  GIO_AON_PIN12_ALT_UART1 = 1,
  GIO_AON_PIN12_ALT_VC_UART2,
  GIO_AON_PIN12_ALT_VC_UART0,
  GIO_AON_PIN12_ALT_VC_SPI0,
  GIO_AON_PIN12_ALT_USB_PWR,
  GIO_AON_PIN12_ALT_VC_UART2_2,
  GIO_AON_PIN12_ALT_VC_SPI3,
} GIO_AON_PIN12_ALT;

typedef enum {
  GIO_AON_PIN13_ALT_BSC_M1 = 1,
  GIO_AON_PIN13_ALT_VC_UART0,
  GIO_AON_PIN13_ALT_UUI,
  GIO_AON_PIN13_ALT_VC_SPI0,
  GIO_AON_PIN13_ALT_ARM_JTAG,
  GIO_AON_PIN13_ALT_VC_UART2,
  GIO_AON_PIN13_ALT_VC_I2C3,
} GIO_AON_PIN13_ALT;

typedef enum {
  GIO_AON_PIN14_ALT_BSC_M1 = 1,
  GIO_AON_PIN14_ALT_AON_GPCLK,
  GIO_AON_PIN14_ALT_VC_UART0,
  GIO_AON_PIN14_ALT_UUI,
  GIO_AON_PIN14_ALT_VC_SPI0,
  GIO_AON_PIN14_ALT_ARM_JTAG,
  GIO_AON_PIN14_ALT_VC_UART2,
  GIO_AON_PIN14_ALT_VC_I2C3,
} GIO_AON_PIN14_ALT;

typedef enum {
  GIO_AON_PIN15_ALT_HDMI_TX0_BSC = 1,
  GIO_AON_PIN15_ALT_HDMI_TX0_AUTO_I2C,
  GIO_AON_PIN15_ALT_BSC_M0,
  GIO_AON_PIN15_ALT_VC_I2C0,
} GIO_AON_PIN15_ALT;

typedef enum {
  GIO_AON_PIN16_ALT_HDMI_TX0_BSC = 1,
  GIO_AON_PIN16_ALT_HDMI_TX0_AUTO_I2C,
  GIO_AON_PIN16_ALT_BSC_M0,
  GIO_AON_PIN16_ALT_VC_I2C0,
} GIO_AON_PIN16_ALT;

typedef enum {
  GIO_AON_PIN17_ALT_HDMI_TX1_BSC = 1,
  GIO_AON_PIN17_ALT_HDMI_TX1_AUTO_I2C,
  GIO_AON_PIN17_ALT_BSC_M1,
  GIO_AON_PIN17_ALT_VC_I2C0,
  GIO_AON_PIN17_ALT_CTL_HDMI_5V,
} GIO_AON_PIN17_ALT;

typedef enum {
  GIO_AON_PIN18_ALT_HDMI_TX1_BSC = 1,
  GIO_AON_PIN18_ALT_HDMI_TX1_AUTO_I2C,
  GIO_AON_PIN18_ALT_BSC_M1,
  GIO_AON_PIN18_ALT_VC_I2C0,
} GIO_AON_PIN18_ALT;

typedef enum {
  GIO_AON_PIN19_ALT_AVS_PMU_BSC = 1,
  GIO_AON_PIN19_ALT_BSC_M2,
  GIO_AON_PIN19_ALT_VC_I2C3,
  GIO_AON_PIN19_ALT_CTL_HDMI_5V,
} GIO_AON_PIN19_ALT;

typedef enum {
  GIO_AON_PIN20_ALT_AVS_PMU_BSC = 1,
  GIO_AON_PIN20_ALT_BSC_M2,
  GIO_AON_PIN20_ALT_VC_I2C3,
} GIO_AON_PIN20_ALT;

#endif // __BCM2712_PINCTRL_H__
